# tmux-claude-bridge Docker Compose Configuration
version: '3.8'

services:
  tmux-bridge:
    build:
      context: .
      dockerfile: Dockerfile
    image: tmux-claude-bridge:latest
    container_name: tmux-claude-bridge
    
    # Environment variables
    environment:
      - PORT=8080
      - TMUX_SESSION=claude-bridge
      - TMUX_PANE=1
      - LOG_LEVEL=info
    
    # Port mapping
    ports:
      - "8080:8080"
    
    # Volume mounts
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
      # Mount tmux socket if running tmux on host
      - /tmp:/tmp:ro
    
    # Network mode for tmux session access
    # Use host network to access host tmux sessions
    network_mode: host
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 64M
    
    # Restart policy
    restart: unless-stopped
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Development container with tmux included
  tmux-bridge-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: tmux-claude-bridge:dev
    container_name: tmux-claude-bridge-dev
    profiles:
      - dev
    
    environment:
      - PORT=8080
      - TMUX_SESSION=claude-bridge
      - TMUX_PANE=1
      - LOG_LEVEL=debug
    
    ports:
      - "8080:8080"
    
    volumes:
      - .:/app
      - /tmp:/tmp
    
    working_dir: /app
    
    # Keep container running for development
    tty: true
    stdin_open: true
    
    # Override entrypoint for development
    command: ["sh", "-c", "while true; do sleep 30; done"]

# Create volumes
volumes:
  logs:
    driver: local
  data:
    driver: local